# Generated by Django 5.0.1 on 2024-01-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_to_guess', models.CharField(max_length=50)),
                ('guessed_letters', models.CharField(default='', max_length=50)),
                ('attempts_left', models.IntegerField(default=10)),
                ('is_winner', models.BooleanField(default=False)),
            ],
        ),
    ]
